## Resize the image

In [56]:
import numpy as np
import cv2 as cv

In [72]:
img = cv.imread("D:\Internship ML\learn and build\class recording\Projects\Open cv\open cv logo.png")

In [73]:
print(type(img))
print(img.shape)
print(img.size)
print(img.ndim)
print(img)
img = cv.resize(img,(500,400))  #resize the image

<class 'numpy.ndarray'>
(600, 487, 3)
876600
3
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [91]:
cv.imshow("image",img)
k = cv.waitKey(0)

### Color to Grayscale

In [90]:
img_grayscale = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
cv.imshow("Gray", img_grayscale)
k = cv.waitKey(0)

In [61]:
print(img_grayscale.shape)
print(img_grayscale.size)
print(img_grayscale.ndim) #dimensions = 2 because no color layer is there

(400, 500)
200000
2


### Thresholding of the image

In [94]:
thr = cv.threshold(img_grayscale, 100,255, cv.THRESH_BINARY)
cv.imshow("Thresholded",thr)
k = cv.waitKey(0)


error: OpenCV(4.6.0) :-1: error: (-5:Bad argument) in function 'imshow'
> Overload resolution failed:
>  - mat is not a numerical tuple
>  - Expected Ptr<cv::cuda::GpuMat> for argument 'mat'
>  - Expected Ptr<cv::UMat> for argument 'mat'


### Applying filter to the image 

In [88]:
filter1 = np.ones((5,5))/55  #creating filter with an array- this filter blurs the original image
filter_image = cv.filter2D(img,ddepth = -1,kernel=filter1)
cv.imshow("Filter image",filter_image)
k = cv.waitKey(0)